os:
  - osx
  # - linux

sudo: required

script:
  - time ./po-util.sh install
  - cd build-test
  - time ~/po-util.sh photon build
  - time ~/po-util.sh electron clean
  - time ~/po-util.sh electron build

addons:
    code_climate:
        repo_token: 029106a12c53af689a6e41dae3f745b02654a46ec5a6d876562c2efb2ea62e4e
